import './geometry.test.js';
import './exports.test.js';
import './validation.test.js';
import './license.test.js';
import './fold.test.js';
import './annotate.test.js';
import './estimate.test.js';
import './sheet.test.js';
import './advice.test.js';
import './tile.test.js';
import './assets.test.js';
import './units.test.js';
import './style.test.js';
import './pack.test.js';
import './cost.test.js';
import './board.test.js';
import './spec.test.js';
import './regions.test.js';
import { report } from './harness.js';
process.exit(report() ? 0 : 1);
